# --- Build stage ---
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# --- Runtime stage ---
FROM nginx:1.25-alpine

# dist を nginx に配置
COPY --from=build /app/dist /usr/share/nginx/html

# 本番用 nginx 設定
COPY ./docker/nginx/nginx.prod.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/server.prod.conf /etc/nginx/conf.d/server.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
