services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${REACT_PORT}:5173"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${POSTGRES_PORT}
      VITE_API_URL: /api
      BROWSER: none

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    working_dir: /src/backend/KazApi.NET
    volumes:
      - ./backend/KazApi.NET:/src/backend/KazApi.NET
      - ./backend/CSLib:/src/backend/CSLib
      - ./backend/KazApi.NET/adapter:/src/backend/KazApi.NET/adapter
    ports:
      - "${API_PORT}:5000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${POSTGRES_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      DOTNET_USE_POLLING_FILE_WATCHER: true
      TZ: Asia/Tokyo

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Tokyo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:${POSTGRES_PORT}"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.dev
    ports:
      - "${NGINX_HTTP_PORT}:80"
    environment:
      - TZ=Asia/Tokyo

  batch-autobattle:
    build:
      context: .
      dockerfile: ./batch/autoBattle/Dockerfile.dev
    container_name: portfolio-batch-autobattle
    restart: "no"

volumes:
  pgdata:
