name: portfolio

services:
  public-api:
    networks:
      - portfolio-net
    environment:
      TZ: Asia/Tokyo

  private-api:
    networks:
      - portfolio-net
    environment:
      TZ: Asia/Tokyo

  db:
    networks:
      - portfolio-net
    environment:
      TZ: Asia/Tokyo

  nginx:
    networks:
      - portfolio-net
    environment:
      TZ: Asia/Tokyo

  batch-auto-battle:
    depends_on:
      - db
    networks:
      - portfolio-net
    environment:
      TZ: Asia/Tokyo

  batch-guitar-crawler:
    depends_on:
      - db
    networks:
      - portfolio-net
    environment:
      TZ: Asia/Tokyo

volumes:
  pg-data:

networks:
  portfolio-net:
