name: portfolio

services:
  frontend:
    networks:
      - portfolio-net

  public-api:
    networks:
      - portfolio-net

  private-api:
    networks:
      - portfolio-net

  db:
    networks:
      - portfolio-net

  nginx:
    networks:
      - portfolio-net

  batch-auto-battle:
    depends_on:
      - db
    networks:
      - portfolio-net

  batch-guitar-crawler:
    depends_on:
      - db
    networks:
      - portfolio-net

  # 新しいジョブを追加する場合はここに追記
  # batch_xxx:

volumes:
  pg-data:

networks:
  portfolio-net:
