FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

# restore用
COPY ./backend/CSLib/CSLib.csproj ./backend/CSLib/
COPY ./backend/Repository/Repository.csproj ./backend/Repository/
COPY ./backend/KazApi.NET/KazApi.csproj ./backend/KazApi.NET/

RUN dotnet restore ./backend/KazApi.NET/KazApi.csproj

# ソースはComposeでマウントするためCOPYしない
WORKDIR /src/backend/KazApi.NET

ENTRYPOINT ["dotnet", "run", "--project", "KazApi.csproj", "--urls", "http://0.0.0.0:5000"]