FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev

RUN rm -rf /src/backend/KazApi.NET/bin /src/backend/KazApi.NET/obj \
           /src/backend/CSLib/bin /src/backend/CSLib/obj

WORKDIR /src

# csproj だけコピー（restore キャッシュ用）
COPY ./backend/CSLib/CSLib.csproj ./backend/CSLib/
COPY ./backend/KazApi.NET/KazApi.csproj ./backend/KazApi.NET/

RUN dotnet restore ./backend/KazApi.NET/KazApi.csproj

# ソースは bind mount するので COPY しない

WORKDIR /src/backend/KazApi.NET

ENTRYPOINT ["dotnet", "watch", "--non-interactive", "run", "--urls", "http://0.0.0.0:5000"]
