FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

# restore用
COPY ./backend/CSLib/CSLib.csproj ./backend/CSLib/
COPY ./backend/Repository/Repository.csproj ./backend/Repository/
COPY ./backend/PrivateApi/PrivateApi.csproj ./backend/PrivateApi/

RUN dotnet restore ./backend/PrivateApi/PrivateApi.csproj

# ソースはComposeでマウントするためCOPYしない
WORKDIR /src/backend/PrivateApi

ENTRYPOINT ["dotnet", "run", "--project", "PrivateApi.csproj", "--urls", "http://0.0.0.0:5000"]