FROM golang:1.26.1

RUN apt-get update && \
    apt-get install -y cron

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/guitar ./cmd/guitar

COPY crontab.txt /etc/cron.d/guitar-crawler
RUN chmod 0644 /etc/cron.d/guitar-crawler
RUN crontab /etc/cron.d/guitar-crawler

CMD ["/bin/sh", "-c", "printenv > /etc/environment && exec cron -f"]