# build stage
FROM golang:1.26.1 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/guitar ./cmd/guitar
RUN go build -o /app/batchMonitor ./cmd/batchMonitor
RUN go build -o /app/dbArchiver ./cmd/dbArchiver

# runtime stage
FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        cron \
        ca-certificates \
        postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/guitar /app/guitar
COPY --from=build /app/batchMonitor /app/batchMonitor
COPY --from=build /app/dbArchiver /app/dbArchiver

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN mkdir -p /app/internal/crawler/logs/job
RUN mkdir -p /app/internal/crawler/logs/guitar

CMD ["/entrypoint.sh"]