FROM golang:1.26.1

RUN apt-get update && \
    apt-get install -y \
        cron \
        postgresql-client-17 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/guitar ./cmd/guitar
RUN go build -o /app/batchMonitor ./cmd/batchMonitor
RUN go build -o /app/dbArchiver ./cmd/dbArchiver

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]