events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        # Vite dev server にプロキシ
        location / {
            proxy_pass http://app:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # API へのプロキシ
        location /api/ {
            proxy_pass http://api:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
