import killerBee1 from "../images/monsters/killerBee1.png";
import killerBee2 from "../images/monsters/killerBee2.png";
import killerBee3 from "../images/monsters/killerBee3.png";
import carmilla1 from "../images/monsters/carmilla1.png";
import carmilla2 from "../images/monsters/carmilla2.png";
import daemon1 from "../images/monsters/daemon1.png";
import daemon2 from "../images/monsters/daemon2.png";
import goblin1 from "../images/monsters/goblin1.png"
import goblin2 from "../images/monsters/goblin2.png"
import goblin3 from "../images/monsters/goblin3.png"
import golem1 from "../images/monsters/golem1.png";
import golem2 from "../images/monsters/golem2.png";
import golem3 from "../images/monsters/golem3.png";
import harpy1 from "../images/monsters/harpy1.png";
import harpy2 from "../images/monsters/harpy2.png";
import knight1 from "../images/monsters/knight1.png";
import knight2 from "../images/monsters/knight2.png";
import knight3 from "../images/monsters/knight3.png";
import magician1 from "../images/monsters/magician1.png";
import magician2 from "../images/monsters/magician2.png";
import magician3 from "../images/monsters/magician3.png";
import matango1 from "../images/monsters/matango1.png";
import matango2 from "../images/monsters/matango2.png";
import needleBird1 from "../images/monsters/needleBird1.png";
import needleBird2 from "../images/monsters/needleBird2.png";
import petitDragon1 from "../images/monsters/petitDragon1.png";
import petitDragon2 from "../images/monsters/petitDragon2.png";
import petitDragon3 from "../images/monsters/petitDragon3.png";
import petitDragon4 from "../images/monsters/petitDragon4.png";
import poto1 from "../images/monsters/poto1.png";
import poto2 from "../images/monsters/poto2.png";
import poto3 from "../images/monsters/poto3.png";
import priest1 from "../images/monsters/priest1.png";
import priest2 from "../images/monsters/priest2.png";
import priest3 from "../images/monsters/priest3.png";
import rabi1 from "../images/monsters/rabi1.png";
import rabi2 from "../images/monsters/rabi2.png";
import rabi3 from "../images/monsters/rabi3.png";
import rabi4 from "../images/monsters/rabi4.png";
import slime1 from "../images/monsters/slime1.png";
import slime2 from "../images/monsters/slime2.png";
import slime3 from "../images/monsters/slime3.png";
import sword1 from "../images/monsters/sword1.png";
import sword2 from "../images/monsters/sword2.png";
import sword3 from "../images/monsters/sword3.png";
import wolf1 from "../images/monsters/wolf1.png";
import wolf2 from "../images/monsters/wolf2.png";
import wolf3 from "../images/monsters/wolf3.png";
import duck1 from "../images/monsters/duck1.png";
import duck2 from "../images/monsters/duck2.png";
import mallBear1 from "../images/monsters/mallBear1.png";
import mallBear2 from "../images/monsters/mallBear2.png";
import galBee1 from "../images/monsters/galBee1.png";
import galBee2 from "../images/monsters/galBee2.png";
import galBee3 from "../images/monsters/galBee3.png";
import fisheman1 from "../images/monsters/fisheman1.png";
import fisheman2 from "../images/monsters/fisheman2.png";
import caterpillar1 from "../images/monsters/caterpillar1.png";
import caterpillar2 from "../images/monsters/caterpillar2.png";
import caterpillar3 from "../images/monsters/caterpillar3.png";
import packn1 from "../images/monsters/packn1.png";
import packn2 from "../images/monsters/packn2.png";
import packn3 from "../images/monsters/packn3.png";
import packn4 from "../images/monsters/packn4.png";
import miniDevil1 from "../images/monsters/miniDevil1.png";
import miniDevil2 from "../images/monsters/miniDevil2.png";
import ogreBox1 from "../images/monsters/ogreBox1.png";
import ogreBox2 from "../images/monsters/ogreBox2.png";
import vallette1 from "../images/monsters/vallette1.png";
import vallette2 from "../images/monsters/vallette2.png";
import basilisk1 from "../images/monsters/basilisk1.png";
import basilisk2 from "../images/monsters/basilisk2.png";
import specter1 from "../images/monsters/specter1.png";
import specter2 from "../images/monsters/specter2.png";
import unicornHead1 from "../images/monsters/unicornHead1.png";
import unicornHead2 from "../images/monsters/unicornHead2.png";
import shadow1 from "../images/monsters/shadow1.png";
import shadow2 from "../images/monsters/shadow2.png";
import shadow3 from "../images/monsters/shadow3.png";
import boulder1 from "../images/monsters/boulder1.png";
import boulder2 from "../images/monsters/boulder2.png";
import boulder3 from "../images/monsters/boulder3.png";
import pumpkin1 from "../images/monsters/pumpkin1.png";
import pumpkin2 from "../images/monsters/pumpkin2.png";

interface MonsterDict {
    [key: string]: string | undefined;
}

const monsterImages = (monsterId: string) => {
    const monsterImages: MonsterDict = {};

    monsterImages["monster000"] = ""; // index: 0 (モンスター無し)
    monsterImages["monster001"] = killerBee1;
	monsterImages["monster002"] = killerBee2;
	monsterImages["monster003"] = killerBee3;
	monsterImages["monster004"] = carmilla1;
	monsterImages["monster005"] = carmilla2;
	monsterImages["monster006"] = daemon1;
	monsterImages["monster007"] = daemon2;
	monsterImages["monster008"] = goblin1;
	monsterImages["monster009"] = goblin2;
	monsterImages["monster010"] = goblin3;
	monsterImages["monster011"] = golem1;
	monsterImages["monster012"] = golem2;
	monsterImages["monster013"] = golem3;
	monsterImages["monster014"] = harpy1;
	monsterImages["monster015"] = harpy2;
	monsterImages["monster016"] = knight1;
	monsterImages["monster017"] = knight2;
	monsterImages["monster018"] = knight3;
	monsterImages["monster019"] = magician1;
	monsterImages["monster020"] = magician2;
	monsterImages["monster021"] = magician3;
	monsterImages["monster022"] = matango1;
	monsterImages["monster023"] = matango2;
	monsterImages["monster024"] = needleBird1;
	monsterImages["monster025"] = needleBird2;
	monsterImages["monster026"] = petitDragon1;
	monsterImages["monster027"] = petitDragon2;
	monsterImages["monster028"] = petitDragon3;
	monsterImages["monster029"] = petitDragon4;
	monsterImages["monster030"] = poto1;
	monsterImages["monster031"] = poto2;
	monsterImages["monster032"] = poto3;
	monsterImages["monster033"] = priest1;
	monsterImages["monster034"] = priest2;
	monsterImages["monster035"] = priest3;
	monsterImages["monster036"] = rabi1;
	monsterImages["monster037"] = rabi2;
	monsterImages["monster038"] = rabi3;
	monsterImages["monster039"] = rabi4;
	monsterImages["monster040"] = slime1;
	monsterImages["monster041"] = slime2;
	monsterImages["monster042"] = slime3;
	monsterImages["monster043"] = sword1;
	monsterImages["monster044"] = sword2;
	monsterImages["monster045"] = sword3;
	monsterImages["monster046"] = wolf1;
	monsterImages["monster047"] = wolf2;
	monsterImages["monster048"] = wolf3;
	monsterImages["monster049"] = duck1;
	monsterImages["monster050"] = duck2;
	monsterImages["monster051"] = mallBear1;
	monsterImages["monster052"] = mallBear2;
	monsterImages["monster053"] = galBee1;
	monsterImages["monster054"] = galBee2;
	monsterImages["monster055"] = galBee3;
	monsterImages["monster056"] = fisheman1;
	monsterImages["monster057"] = fisheman2;
	monsterImages["monster058"] = caterpillar1;
	monsterImages["monster059"] = caterpillar2;
	monsterImages["monster060"] = caterpillar3;
	monsterImages["monster061"] = packn1;
	monsterImages["monster062"] = packn2;
	monsterImages["monster063"] = packn3;
	monsterImages["monster064"] = packn4;
	monsterImages["monster065"] = miniDevil1;
	monsterImages["monster066"] = miniDevil2;
	monsterImages["monster067"] = ogreBox1;
	monsterImages["monster068"] = ogreBox2;
	monsterImages["monster069"] = vallette1;
	monsterImages["monster070"] = vallette2;
	monsterImages["monster071"] = basilisk1;
	monsterImages["monster072"] = basilisk2;
	monsterImages["monster073"] = specter1;
	monsterImages["monster074"] = specter2;
	monsterImages["monster075"] = unicornHead1;
	monsterImages["monster076"] = unicornHead2;
	monsterImages["monster077"] = shadow1;
	monsterImages["monster078"] = shadow2;
	monsterImages["monster079"] = shadow3;
	monsterImages["monster080"] = boulder1;
	monsterImages["monster081"] = boulder2;
	monsterImages["monster082"] = boulder3;
	monsterImages["monster083"] = pumpkin1;
	monsterImages["monster084"] = pumpkin2;

    return monsterImages[monsterId];
}

export default monsterImages;